name: "Release packaging"

on:
  push:

jobs:
  build:

    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '10.x'

      - name: Install dependencies
        run: yarn install

      - name: Package
        run: |
          yarn build
          mv dist nominatim-ui
          tar czf nominatim-ui.tar.gz nominatim-ui
          zip -qr nominatim-ui.zip nominatim-ui

      - uses: actions/upload-artifact@v2
        with:
          name: packages
          path: |
            nominatim-ui.tar.gz
            nominatim-ui.zip
          retention-days: 1
