name: "Release packaging"

on:
  release:
    type: [published]

jobs:
  build:

    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '10.x'

      - name: Install dependencies
        run: yarn install

      - name: Package
        run: |
          yarn build
          mv dist nominatim-ui
          mkdir artifacts
          tar czf artifacts/nominatim-ui-${VERSION}.tar.gz nominatim-ui
          zip -qr artifacts/nominatim-ui-${VERSION}.zip nominatim-ui
        env:
          VERSION: ${{ github.ref }}


      - uses: AButler/upload-release-assets@v2.0
        with:
          files: 'artifacts/*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
